qdrouter:
  image: gordons/qpid-dispatch:0.6.0-rc1
  ports:
    - "15672:5672"
config:
  image: eclipsehono/example-config:0.1-SNAPSHOT
hono:
  image: hono/server:0.1-SNAPSHOT
  ports:
    - "5672:5672"
  links:
    - qdrouter
  environment:
    - HONO_TELEMETRY_DOWNSTREAM_HOST=qdrouter
  volumes_from:
    - config