rabbitmq:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"
dispatcher:
  image: hono/dispatcher:0.1-SNAPSHOT
  links:
    - rabbitmq
  environment:
    - AMQP_URI=amqp://rabbitmq:5672

