qpid-config:
  image: eclipsehono/qpid-default-config:0.1-SNAPSHOT
qpid-sasldb:
  image: eclipsehono/qpid-sasldb:0.1-SNAPSHOT
hono-config:
  image: eclipsehono/hono-default-config:0.1-SNAPSHOT
qdrouter:
  image: gordons/qpid-dispatch:0.6.0
  ports:
    - "15672:5672"
  volumes_from:
    - qpid-config
    - qpid-sasldb
hono:
  image: eclipsehono/hono-server:0.1-SNAPSHOT
  ports:
    - "5672:5672"
  links:
    - qdrouter
  environment:
    - HONO_PERMISSIONS_PATH=file:/etc/hono/permissions.json
    - HONO_MAXINSTANCES=1
    - LOGGING_CONFIG=file:///etc/hono/logback-spring.xml
    - SPRING_CONFIG_LOCATION=file:/etc/hono/
    - SPRING_PROFILES_ACTIVE=default,dev
  volumes_from:
    - hono-config

rest-adapter:
  image: eclipsehono/hono-adapter-rest-vertx:0.1-SNAPSHOT
  ports:
    - "8080:8080"
  links:
    - hono
  environment:
    - HONO_CLIENT_HOST=hono
    - HONO_CLIENT_PORT=5672
    - HONO_CLIENT_USERNAME=hono-client
    - HONO_CLIENT_PASSWORD=secret
    - HONO_HTTP_BINDADDRESS=0.0.0.0
    - HONO_MAXINSTANCES=1
    - SPRING_PROFILES_ACTIVE=dev