qpid-config:
  image: eclipsehono/qpid-default-config:0.1-SNAPSHOT
qpid-sasldb:
  image: eclipsehono/qpid-sasldb:0.1-SNAPSHOT
hono-config:
  image: eclipsehono/hono-default-config:0.1-SNAPSHOT
qdrouter:
  image: gordons/qpid-dispatch:0.6.0
  ports:
    - "15672:5672"
  volumes_from:
    - qpid-config
    - qpid-sasldb
hono:
  image: eclipsehono/hono-server:0.1-SNAPSHOT
  ports:
    - "5672:5672"
  links:
    - qdrouter
  environment:
    - SPRING_CONFIG_LOCATION=file:/etc/hono/
    - HONO_PERMISSIONS_PATH=file:/etc/hono/permissions.json
    - HONO_TELEMETRY_DOWNSTREAM_HOST=qdrouter
    - HONO_MAXINSTANCES=2
  volumes_from:
    - hono-config

rest-adapter:
  image: eclipsehono/hono-adapter-rest-vertx:0.1-SNAPSHOT
  ports:
    - "8080:8080"
  links:
    - hono
  environment:
    - HONO_HTTP_BINDADDRESS=0.0.0.0
    - HONO_MAXINSTANCES=1
    - HONO_SERVER_HOST=hono
    - HONO_USER=hono-client
    - HONO_PASSWORD=secret
    - SPRING_PROFILES_ACTIVE=dev